function escapeHtml(value: string): string {
  return value
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&#39;');
}

function createBrandMark(): string {
  return [
    '<svg viewBox="0 0 64 64" role="img" aria-label="家庭资产负债表">',
    '<defs>',
    '<linearGradient id="hbs-gradient" x1="10%" y1="10%" x2="90%" y2="90%">',
    '<stop offset="0%" stop-color="#2563eb" />',
    '<stop offset="100%" stop-color="#0f766e" />',
    '</linearGradient>',
    '</defs>',
    '<rect x="6" y="6" width="52" height="52" rx="16" fill="url(#hbs-gradient)" />',
    '<path d="M20 31.5 32 20l12 11.5v12.5a2 2 0 0 1-2 2h-5.5V37h-9v9H22a2 2 0 0 1-2-2Z" fill="#f8fafc" />',
    '<path d="M26 46V34h12v12" fill="none" stroke="#0f172a" stroke-width="2.5" stroke-linejoin="round" />',
    '<circle cx="46" cy="18" r="7" fill="#facc15" />',
    '<path d="M42.5 18h7" stroke="#0f172a" stroke-width="2" stroke-linecap="round" />',
    '<path d="M46 14.5v7" stroke="#0f172a" stroke-width="2" stroke-linecap="round" />',
    '</svg>',
  ].join('');
}

function createShell(options: {
  eyebrow: string;
  title: string;
  description: string;
  statusLabel: string;
  statusTitle: string;
  statusBody: string;
  sideTitle: string;
  sideBody: string;
  footerNote: string;
  steps: string[];
  tone: 'loading' | 'error';
  actions?: string;
  script?: string;
}): string {
  const toneClass = options.tone === 'loading' ? 'tone-loading' : 'tone-error';
  const stepsMarkup = options.steps
    .map(
      (step, index) => `
        <li class="step" data-step="${index}" data-active="${index === 0}">
          <span class="step-index">0${index + 1}</span>
          <span class="step-text">${step}</span>
        </li>
      `
    )
    .join('');

  return [
    '<!doctype html>',
    '<html lang="zh-CN">',
    '<head>',
    '<meta charset="utf-8">',
    '<meta name="viewport" content="width=device-width, initial-scale=1">',
    '<title>家庭资产负债表</title>',
    '<style>',
    ':root {',
    '  --bg-top: #f4efe5;',
    '  --bg-bottom: #f7f8fc;',
    '  --ink: #132238;',
    '  --muted: #5f6e82;',
    '  --panel: rgba(255, 251, 245, 0.8);',
    '  --line: rgba(19, 34, 56, 0.12);',
    '  --accent: #1f7a6b;',
    '  --accent-strong: #2257d4;',
    '  --accent-soft: rgba(34, 87, 212, 0.12);',
    '  --gold: #d3a03d;',
    '  --shadow: 0 32px 80px rgba(20, 33, 61, 0.12);',
    '  --error: #b5473c;',
    '}',
    '* { box-sizing: border-box; }',
    'html, body { height: 100%; }',
    'body {',
    '  margin: 0;',
    '  min-height: 100vh;',
    '  font-family: "Avenir Next", "PingFang SC", "Helvetica Neue", sans-serif;',
    '  color: var(--ink);',
    '  background:',
    '    radial-gradient(circle at top left, rgba(211, 160, 61, 0.18), transparent 26%),',
    '    radial-gradient(circle at 85% 18%, rgba(34, 87, 212, 0.16), transparent 24%),',
    '    linear-gradient(160deg, var(--bg-top), var(--bg-bottom));',
    '  overflow: hidden;',
    '}',
    'body::before {',
    '  content: "";',
    '  position: fixed;',
    '  inset: 0;',
    '  background-image:',
    '    linear-gradient(rgba(19, 34, 56, 0.03) 1px, transparent 1px),',
    '    linear-gradient(90deg, rgba(19, 34, 56, 0.03) 1px, transparent 1px);',
    '  background-size: 32px 32px;',
    '  mask-image: linear-gradient(180deg, rgba(0,0,0,.6), transparent 85%);',
    '}',
    '.shell {',
    '  position: relative;',
    '  display: grid;',
    '  grid-template-columns: minmax(0, 1.15fr) minmax(320px, 0.85fr);',
    '  gap: 40px;',
    '  align-items: center;',
    '  min-height: 100vh;',
    '  padding: 56px 72px;',
    '}',
    '.hero { position: relative; z-index: 1; max-width: 820px; }',
    '.eyebrow {',
    '  display: inline-flex;',
    '  align-items: center;',
    '  gap: 10px;',
    '  padding: 8px 14px;',
    '  border: 1px solid var(--line);',
    '  border-radius: 999px;',
    '  background: rgba(255, 255, 255, 0.55);',
    '  color: var(--muted);',
    '  font-size: 13px;',
    '  letter-spacing: 0.08em;',
    '  text-transform: uppercase;',
    '}',
    '.eyebrow::before {',
    '  content: "";',
    '  width: 9px;',
    '  height: 9px;',
    '  border-radius: 999px;',
    '  background: linear-gradient(135deg, var(--gold), var(--accent));',
    '  box-shadow: 0 0 0 6px rgba(31, 122, 107, 0.08);',
    '}',
    'h1 {',
    '  margin: 24px 0 16px;',
    '  font-family: "Iowan Old Style", "Baskerville", "Times New Roman", serif;',
    '  font-size: clamp(52px, 7vw, 86px);',
    '  line-height: 0.98;',
    '  letter-spacing: -0.05em;',
    '}',
    '.description {',
    '  max-width: 680px;',
    '  margin: 0 0 28px;',
    '  color: var(--muted);',
    '  font-size: 21px;',
    '  line-height: 1.7;',
    '}',
    '.steps {',
    '  display: grid;',
    '  grid-template-columns: repeat(3, minmax(0, 1fr));',
    '  gap: 14px;',
    '  margin: 36px 0 24px;',
    '  padding: 0;',
    '  list-style: none;',
    '}',
    '.step {',
    '  position: relative;',
    '  min-height: 112px;',
    '  padding: 18px 18px 20px;',
    '  border-radius: 24px;',
    '  border: 1px solid rgba(19, 34, 56, 0.08);',
    '  background: rgba(255, 255, 255, 0.56);',
    '  box-shadow: inset 0 1px 0 rgba(255,255,255,.5);',
    '  transition: transform .35s ease, border-color .35s ease, background .35s ease;',
    '}',
    '.step[data-active="true"] {',
    '  transform: translateY(-4px);',
    '  border-color: rgba(34, 87, 212, 0.24);',
    '  background: linear-gradient(180deg, rgba(255,255,255,.92), rgba(240, 247, 255, .78));',
    '}',
    '.step-index {',
    '  display: inline-flex;',
    '  align-items: center;',
    '  justify-content: center;',
    '  width: 36px;',
    '  height: 36px;',
    '  border-radius: 14px;',
    '  background: rgba(19, 34, 56, 0.08);',
    '  color: var(--muted);',
    '  font-size: 14px;',
    '  font-weight: 700;',
    '}',
    '.step[data-active="true"] .step-index {',
    '  background: linear-gradient(135deg, var(--accent-strong), var(--accent));',
    '  color: #fff;',
    '  box-shadow: 0 10px 24px rgba(34, 87, 212, 0.24);',
    '}',
    '.step-text {',
    '  display: block;',
    '  margin-top: 18px;',
    '  font-size: 17px;',
    '  line-height: 1.5;',
    '}',
    '.footer-note {',
    '  color: var(--muted);',
    '  font-size: 15px;',
    '}',
    '.actions {',
    '  display: flex;',
    '  flex-wrap: wrap;',
    '  gap: 12px;',
    '  margin-top: 24px;',
    '}',
    '.action-button {',
    '  appearance: none;',
    '  border: 1px solid rgba(19, 34, 56, 0.12);',
    '  border-radius: 999px;',
    '  background: rgba(255, 255, 255, 0.78);',
    '  color: var(--ink);',
    '  cursor: pointer;',
    '  font: inherit;',
    '  font-size: 15px;',
    '  font-weight: 600;',
    '  padding: 12px 20px;',
    '  transition: transform .2s ease, border-color .2s ease, background .2s ease;',
    '}',
    '.action-button:hover {',
    '  transform: translateY(-1px);',
    '  border-color: rgba(34, 87, 212, 0.24);',
    '  background: rgba(255, 255, 255, 0.92);',
    '}',
    '.action-button:disabled {',
    '  cursor: wait;',
    '  opacity: 0.72;',
    '  transform: none;',
    '}',
    '.panel {',
    '  position: relative;',
    '  z-index: 1;',
    '  overflow: hidden;',
    '  border-radius: 34px;',
    '  border: 1px solid rgba(19, 34, 56, 0.08);',
    '  background: var(--panel);',
    '  box-shadow: var(--shadow);',
    '  backdrop-filter: blur(18px);',
    '  padding: 30px 30px 28px;',
    '}',
    '.panel::before {',
    '  content: "";',
    '  position: absolute;',
    '  inset: -20% auto auto -10%;',
    '  width: 180px;',
    '  height: 180px;',
    '  border-radius: 999px;',
    '  background: radial-gradient(circle, rgba(34, 87, 212, 0.22), transparent 70%);',
    '}',
    '.brand-row {',
    '  display: flex;',
    '  align-items: center;',
    '  gap: 18px;',
    '}',
    '.brand-mark {',
    '  width: 68px;',
    '  height: 68px;',
    '  flex: none;',
    '  filter: drop-shadow(0 12px 24px rgba(34, 87, 212, 0.16));',
    '}',
    '.brand-copy small {',
    '  display: block;',
    '  color: var(--muted);',
    '  letter-spacing: 0.08em;',
    '  text-transform: uppercase;',
    '  font-size: 12px;',
    '}',
    '.brand-copy strong {',
    '  display: block;',
    '  margin-top: 6px;',
    '  font-size: 28px;',
    '  line-height: 1.2;',
    '}',
    '.status-chip {',
    '  margin-top: 26px;',
    '  display: inline-flex;',
    '  align-items: center;',
    '  gap: 10px;',
    '  padding: 10px 14px;',
    '  border-radius: 999px;',
    '  background: rgba(255,255,255,0.72);',
    '  border: 1px solid rgba(19, 34, 56, 0.08);',
    '  color: var(--muted);',
    '  font-size: 13px;',
    '}',
    '.status-chip::before {',
    '  content: "";',
    '  width: 10px;',
    '  height: 10px;',
    '  border-radius: 999px;',
    '  background: var(--accent);',
    '  box-shadow: 0 0 0 7px rgba(31, 122, 107, 0.12);',
    '  animation: pulse 1.8s ease-in-out infinite;',
    '}',
    '.progress-track {',
    '  position: relative;',
    '  height: 12px;',
    '  margin-top: 24px;',
    '  border-radius: 999px;',
    '  background: rgba(19, 34, 56, 0.08);',
    '  overflow: hidden;',
    '}',
    '.progress-track::before {',
    '  content: "";',
    '  position: absolute;',
    '  inset: 0;',
    '  background: linear-gradient(90deg, rgba(34, 87, 212, 0.12), rgba(31, 122, 107, 0.82), rgba(211, 160, 61, 0.28));',
    '  transform: translateX(-60%);',
    '  animation: sweep 2s ease-in-out infinite;',
    '}',
    '.status-title {',
    '  margin: 26px 0 8px;',
    '  font-size: 24px;',
    '  font-weight: 700;',
    '}',
    '.status-body, .side-body {',
    '  margin: 0;',
    '  color: var(--muted);',
    '  font-size: 16px;',
    '  line-height: 1.7;',
    '}',
    '.side-card {',
    '  margin-top: 26px;',
    '  padding: 20px 22px;',
    '  border-radius: 24px;',
    '  background: rgba(19, 34, 56, 0.04);',
    '  border: 1px solid rgba(19, 34, 56, 0.08);',
    '}',
    '.side-title {',
    '  margin: 0 0 10px;',
    '  font-size: 15px;',
    '  color: var(--muted);',
    '  letter-spacing: 0.06em;',
    '  text-transform: uppercase;',
    '}',
    '.tone-error {',
    '  --accent: #b5473c;',
    '  --accent-strong: #d16a43;',
    '  --accent-soft: rgba(181, 71, 60, 0.12);',
    '  --panel: rgba(255, 248, 246, 0.88);',
    '}',
    '.tone-error .status-chip::before {',
    '  background: var(--error);',
    '  box-shadow: 0 0 0 7px rgba(181, 71, 60, 0.12);',
    '}',
    '@keyframes pulse {',
    '  0%, 100% { transform: scale(1); opacity: 1; }',
    '  50% { transform: scale(1.18); opacity: .72; }',
    '}',
    '@keyframes sweep {',
    '  0% { transform: translateX(-58%); }',
    '  50% { transform: translateX(18%); }',
    '  100% { transform: translateX(100%); }',
    '}',
    '@media (max-width: 1100px) {',
    '  .shell { grid-template-columns: 1fr; padding: 36px 28px; gap: 24px; }',
    '  .steps { grid-template-columns: 1fr; }',
    '  h1 { font-size: clamp(42px, 12vw, 64px); }',
    '  .description { font-size: 18px; }',
    '}',
    '</style>',
    '</head>',
    `<body class="${toneClass}">`,
    '<main class="shell">',
    '<section class="hero">',
    `<span class="eyebrow">${options.eyebrow}</span>`,
    `<h1>${options.title}</h1>`,
    `<p class="description">${options.description}</p>`,
    `<ol class="steps">${stepsMarkup}</ol>`,
    options.actions ?? '',
    `<p class="footer-note">${options.footerNote}</p>`,
    '</section>',
    '<aside class="panel">',
    '<div class="brand-row">',
    `<div class="brand-mark">${createBrandMark()}</div>`,
    '<div class="brand-copy">',
    '<small>Desktop Workspace</small>',
    '<strong>家庭资产负债表</strong>',
    '</div>',
    '</div>',
    `<div class="status-chip">${options.statusLabel}</div>`,
    '<div class="progress-track" aria-hidden="true"></div>',
    `<h2 class="status-title" data-status-title>${options.statusTitle}</h2>`,
    `<p class="status-body" data-status-body>${options.statusBody}</p>`,
    '<section class="side-card">',
    `<h3 class="side-title">${options.sideTitle}</h3>`,
    `<p class="side-body">${options.sideBody}</p>`,
    '</section>',
    '</aside>',
    '</main>',
    options.script ?? '',
    '</body>',
    '</html>',
  ].join('');
}

export function createLoadingPage(): string {
  const script = [
    '<script>',
    'const states = [',
    '  { title: "正在连接本地服务", body: "我们正在唤醒只运行在你设备上的本地服务，确保所有资产数据先在本机准备完成。" },',
    '  { title: "正在载入资产数据", body: "应用会检查本地数据库、迁移状态和最近快照，让首页打开后就能直接进入工作状态。" },',
    '  { title: "正在准备桌面工作台", body: "最后一步会把窗口、导航和图表资源接好。首次启动通常会略慢，之后会明显更快。" },',
    '];',
    'const stepNodes = Array.from(document.querySelectorAll("[data-step]"));',
    'const titleNode = document.querySelector("[data-status-title]");',
    'const bodyNode = document.querySelector("[data-status-body]");',
    'let current = 0;',
    'window.setInterval(() => {',
    '  current = (current + 1) % states.length;',
    '  stepNodes.forEach((node, index) => {',
    '    node.setAttribute("data-active", index === current ? "true" : "false");',
    '  });',
    '  if (titleNode) titleNode.textContent = states[current].title;',
    '  if (bodyNode) bodyNode.textContent = states[current].body;',
    '}, 1700);',
    '</script>',
  ].join('');

  return createShell({
    eyebrow: 'Local-first personal finance workspace',
    title: '正在启动 家庭资产负债表',
    description:
      '我们正在唤醒本地服务、载入资产数据，并为你准备桌面工作台。整个过程只发生在你的设备内。',
    statusLabel: '本地私有模式',
    statusTitle: '正在连接本地服务',
    statusBody:
      '启动完成后，所有页面会直接切换进正式应用界面；你不需要再手动打开浏览器或启动任何命令。',
    sideTitle: '本次启动会做什么',
    sideBody:
      '初始化本地数据库连接、恢复桌面应用状态，并将前端工作台与本地 API 重新绑定，确保接下来页面响应稳定。',
    footerNote: '如果这是首次安装，启动可能会比之后略慢一些；完成后再次打开通常会更快。',
    steps: ['正在连接本地服务', '正在载入资产数据', '正在准备桌面工作台'],
    tone: 'loading',
    script,
  });
}

export function createErrorPage(message: string): string {
  const script = [
    '<script>',
    'const retryButton = document.querySelector("[data-retry-bootstrap]");',
    'retryButton?.addEventListener("click", async () => {',
    '  retryButton.setAttribute("disabled", "true");',
    '  retryButton.textContent = "正在重试...";',
    '  try {',
    '    const retry = window.__HBS_DESKTOP__?.bootstrap?.retry;',
    '    if (typeof retry === "function") {',
    '      await retry();',
    '      return;',
    '    }',
    '  } catch (_error) {',
    '    // Keep the same error page visible and let the user try again.',
    '  }',
    '  retryButton.removeAttribute("disabled");',
    '  retryButton.textContent = "重新尝试启动";',
    '});',
    '</script>',
  ].join('');

  return createShell({
    eyebrow: 'Launch issue detected',
    title: '应用启动失败',
    description:
      '桌面工作台还没有顺利完成初始化。别担心，这通常是一次性的启动阻塞，我们先给你最直接的处理建议。',
    statusLabel: '需要人工确认',
    statusTitle: '可以先在应用内重试启动',
    statusBody:
      '如果应用内重试后仍失败，再根据手册检查系统是否阻止了应用运行，或把下面的错误信息发给我们继续排查。',
    sideTitle: '错误详情',
    sideBody: escapeHtml(message),
    footerNote: '如果应用内重试仍失败，再退出应用后重新打开；若首次安装被系统拦截，请到系统设置里允许运行。',
    steps: ['先尝试应用内重试', '如系统拦截则去设置允许', '仍有问题时反馈错误详情'],
    tone: 'error',
    actions:
      '<div class="actions"><button type="button" class="action-button" data-retry-bootstrap>重新尝试启动</button></div>',
    script,
  });
}
