export {
  buildExpectedAssetName,
  compareVersions,
  pickUpdateCandidate,
  toDownloadErrorState,
  toInstallErrorState,
  toNetworkDegradedState,
  toValidationErrorState,
  type GithubRelease,
  type GithubReleaseAsset,
  type PickUpdateCandidateOptions,
  type UpdateAssetCandidate,
  type UpdateCandidate,
  type UpdateErrorKind,
} from './update-workflow.ts';
